import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const items = [
{
    id: "ca3fc346-ca34-480e-8d73-22265e9a820b",
    title: "Tênis Adidas VL Court Woody EL C Infantil",
    description: "Tênis infantil Adidas VL Court Woody EL C.",
    category: "Calçados",
    priceCents: 332.49,
    imageUrl: "",
    size: "25",
    storeUrl: "https://www.magicfeet.com.br/tenis-adidas-vl-court-woody-el-c-infantil-jq438-2-400/p",
},
{
    id: "7c35a475-10c7-4450-9a92-20d1a4772d59",
    title: "Tênis Adidas VL Court 3.0 CF Infantil",
    description: "Tênis infantil Adidas VL Court 3.0 CF.",
    category: "Calçados",
    priceCents: 284.99,
    imageUrl: "",
    size: "25",
    storeUrl: "https://www.magicfeet.com.br/tenis-adidas-vl-court-3-0-cf-infantil-ih396-6-100/p",
},
{
    id: "f4d4de83-56c5-491b-914e-ed523a173394",
    title: "Tênis Veja Small Volley Suede Infantil",
    description: "Tênis infantil Veja Small Volley Suede.",
    category: "Calçados",
    priceCents: 339.99,
    imageUrl: "",
    size: "26",
    storeUrl: "https://www.magicfeet.com.br/tenis-veja-small-volley-suede-infantil-21018-0-300/p",
},
{
    id: "da33df42-6d9e-420c-b59a-81bd0fcf4793",
    title: "Tênis Converse Chuck Taylor All Star Velcro TD Infantil",
    description: "Tênis infantil Converse Chuck Taylor All Star com velcro.",
    category: "Calçados",
    priceCents: 0,
    imageUrl: "",
    size: "",
    storeUrl: "https://www.magicfeet.com.br/tenis-converse-chuck-taylor-all-star-velcro-td-infantil-ck041-8-004/p",
},
{
    id: "aa6b6b95-bf9b-414a-b56f-9de7e1fa564b",
    title: "Tênis Adidas VL Court 3.0 CF Infantil",
    description: "Tênis infantil Adidas VL Court 3.0 CF.",
    category: "Calçados",
    priceCents: 284.99,
    imageUrl: "",
    size: "25",
    storeUrl: "https://www.magicfeet.com.br/tenis-adidas-vl-court-3-0-cf-infantil-id915-6-001/p",
},
{
    id: "6804f7c1-c9f8-433f-8f43-cc915707dbbb",
    title: "Chinelo Nike Kawa Slide BT Infantil",
    description: "Chinelo infantil Nike Kawa Slide.",
    category: "Calçados",
    priceCents: 189.99,
    imageUrl: "",
    size: "25",
    storeUrl: "https://www.magicfeet.com.br/chinelo-nike-kawa-slide-bt-infantil-fj881-1-401/p",
},
{
    id: "df592186-2579-400c-a6ab-da382f1e583c",
    title: "Sandália Crocs Crocband Clog TD Infantil",
    description: "Sandália infantil Crocs Crocband.",
    category: "Calçados",
    priceCents: 256.49,
    imageUrl: "",
    size: "26",
    storeUrl: "https://www.magicfeet.com.br/sandalia-crocs-crocband-clog-td-infantil-20700-5-485/p",
},
{
    id: "ba12093c-4daf-4078-a6d8-538f3c955cc0",
    title: "Sandália Crocs Crocband Clog T Infantil",
    description: "Sandália infantil Crocs Crocband.",
    category: "Calçados",
    priceCents: 0,
    imageUrl: "",
    size: "",
    storeUrl: "https://www.magicfeet.com.br/sandalia-crocs-crocband-clog-t-infantil-20700-5-126/p",
},
{
    id: "ea77de1a-8cc9-41a9-a761-fad32b519082",
    title: "Sandália Infantil Bibi Baby Soft II Marrom",
    description: "Sandália infantil Bibi Baby Soft II.",
    category: "Calçados",
    priceCents: 0,
    imageUrl: "",
    size: "",
    storeUrl: "https://www.bibi.com/sandalia-infantil-bibi-baby-soft-ii-marrom/p",
},
{
    id: "2c853fd3-8ed4-4c63-8021-ab004e848162",
    title: "Tênis Masculino CB Vol.2",
    description: "Tênis masculino infantil CB Vol.2.",
    category: "Calçados",
    priceCents: 0,
    imageUrl: "",
    size: "",
    storeUrl: "https://loja.milon.com.br/tenis-masculino-cb-vol2-546-307971/p",
},

// ===================== BRINQUEDOS =====================
{
    id: "36e5402a-ef4c-4ae7-b245-9dc2ffdd803b",
    title: "Assento Redutor Privadinha Sanitário Infantil",
    description: "Assento redutor infantil para vaso sanitário.",
    category: "Brinquedos",
    priceCents: 0,
    imageUrl: "",
    size: "",
    storeUrl: "https://www.amazon.com.br/Assento-Redutor-Privadinha-Sanit%C3%A1rio-Infantil/dp/B0FKBD4BNG/",
},
{
    id: "2a6d27d1-674b-42f9-b888-410bb81bb6d9",
    title: "Conjunto de Carrinhos Hot Wheels Mattel",
    description: "Kit com conjunto de carrinhos Hot Wheels da Mattel.",
    category: "Brinquedos",
    priceCents: 0,
    imageUrl: "",
    size: "",
    storeUrl: "https://www.amazon.com.br/Conjunto-Carrinhos-Wheels-Mattel-H7045/dp/B0007R4J30/",
},
{
    id: "38bb01e0-7b07-4697-b9e9-9f851a6b5b8c",
    title: "Triciclo Infantil com Cestinha",
    description: "Triciclo infantil masculino com cestinha.",
    category: "Brinquedos",
    priceCents: 0,
    imageUrl: "",
    size: "",
    storeUrl: "https://www.amazon.com.br/Triciclo-Infantil-Cestinha-Bicicleta-Masculina/dp/B0H2JQZX5K/",
},
{
    id: "4abdfd9c-7e24-4a97-ae95-bebc8c87c74a",
    title: "Carrinho de Rolimã Infantil Vermelho",
    description: "Carrinho de rolimã infantil na cor vermelha.",
    category: "Brinquedos",
    priceCents: 0,
    imageUrl: "",
    size: "",
    storeUrl: "https://www.amazon.com.br/Carrinho-Infantil-Rodopio-Suporta-Vermelho/dp/B0GZSCLKYF/",
},
{
    id: "e5efcd36-e5cc-40b1-a44b-a3168bcd35a0",
    title: "Patinete Infantil Aviãozinho Ajustável",
    description: "Patinete infantil formato aviãozinho, ajustável, com luz e som.",
    category: "Brinquedos",
    priceCents: 0,
    imageUrl: "",
    size: "",
    storeUrl: "https://www.amazon.com.br/DM-Toys-Patinete-Aviaozinho-Ajustavel/dp/B0DJS66HVG/",
},
{
    id: "c1eb8316-c67e-41a8-9877-998912af38c6",
    title: "Blocos Magnéticos de Construção",
    description: "Kit de blocos magnéticos para construção.",
    category: "Brinquedos",
    priceCents: 0,
    imageUrl: "",
    size: "",
    storeUrl: "https://www.amazon.com.br/Blocos-Constru%C3%A7%C3%A3o-Magn%C3%A9ticos-Brastoy-Brinquedos/dp/B097K16GKC/",
},
{
    id: "81b0216a-94b2-4538-8efd-f01b713a676a",
    title: "Mini Quadriciclo Elétrico Infantil 6V",
    description: "Mini quadriciclo elétrico infantil a bateria 6V, com luz e música.",
    category: "Brinquedos",
    priceCents: 0,
    imageUrl: "",
    size: "",
    storeUrl: "https://www.mercadolivre.com.br/mini-quadriciclo-eletrico-infantil-bateria-6v-luz-e-musica-cor-laranja-voltagem-do-carregador-110v220v-brinqkids/p/MLB43400696",
},
{
    id: "54a5a121-f197-4bdf-83e1-12cd1a2a18d4",
    title: "Mini Moto Elétrica Infantil 6V Preta",
    description: "Mini moto elétrica infantil 6V, cor preta, com empurrador.",
    category: "Brinquedos",
    priceCents: 0,
    imageUrl: "",
    size: "",
    storeUrl: "https://www.mercadolivre.com.br/mini-moto-eletrica-infantil-6v-preta-speed-com-empurrador-preto/p/MLB62101177",
},
{
    id: "3d618a9e-40aa-4b87-8c3d-b55ea008e7fd",
    title: "Bateria Musical Infantil Rock Party",
    description: "Instrumento infantil bateria musical Rock Party, DM Toys.",
    category: "Brinquedos",
    priceCents: 0,
    imageUrl: "",
    size: "",
    storeUrl: "https://www.mercadolivre.com.br/bateria-musical-instrumento-infantil-rock-party-preta-dm-toys-dmt6066pr/p/MLB23531681",
},
{
    id: "287de57e-6438-4dda-904a-3f647227312d",
    title: "Mochila Kids Carros Masterbag",
    description: "Mochila infantil tema carros, Masterbag Kids.",
    category: "Brinquedos",
    priceCents: 0,
    imageUrl: "",
    size: "",
    storeUrl: "https://www.bebefacil.com.br/produto/mochila-kids-carros-masterbag-kids-4725",
},

// ===================== ROUPAS =====================
{
    id: "4c617836-2ab0-444f-a3d7-1edd5d97b557",
    title: "Conjunto Masculino (Milon 2001697)",
    description: "Conjunto masculino infantil Milon.",
    category: "Roupas",
    priceCents: 0,
    imageUrl: "",
    size: "",
    storeUrl: "https://loja.milon.com.br/conjunto-masculino-2001697-319332/p",
},
{
    id: "e5d8d426-d92e-4273-8e14-90b2e52afddf",
    title: "Conjunto Masculino (Milon 3000937)",
    description: "Conjunto masculino infantil Milon.",
    category: "Roupas",
    priceCents: 0,
    imageUrl: "",
    size: "",
    storeUrl: "https://loja.milon.com.br/conjunto-masculino-3000937-315473/p",
},
{
    id: "a17eb5c6-538a-444a-bd66-bf635e20018d",
    title: "Conjunto Masculino (Milon 2001708)",
    description: "Conjunto masculino infantil Milon.",
    category: "Roupas",
    priceCents: 0,
    imageUrl: "",
    size: "",
    storeUrl: "https://loja.milon.com.br/conjunto-masculino-2001708-308376/p",
},
{
    id: "3ff808a5-a2dc-4b9b-ace4-47b62b9fad1d",
    title: "Conjunto Masculino (Milon 3000715)",
    description: "Conjunto masculino infantil Milon.",
    category: "Roupas",
    priceCents: 0,
    imageUrl: "",
    size: "",
    storeUrl: "https://loja.milon.com.br/conjunto-masculino-3000715-306882/p",
},
{
    id: "6d1f0a74-419c-43bb-b3f2-d5187cc85714",
    title: "Conjunto Masculino (Milon 2001325)",
    description: "Conjunto masculino infantil Milon.",
    category: "Roupas",
    priceCents: 0,
    imageUrl: "",
    size: "",
    storeUrl: "https://loja.milon.com.br/conjunto-masculino-2001325-299471/p",
},
{
    id: "2549707c-ffdc-419a-a67b-ae218a8bf9b9",
    title: "Conjunto Masculino (Milon 2001532)",
    description: "Conjunto masculino infantil Milon.",
    category: "Roupas",
    priceCents: 0,
    imageUrl: "",
    size: "",
    storeUrl: "https://loja.milon.com.br/conjunto-masculino-2001532-318542/p",
},
{
    id: "dea3dff9-34b3-4513-9b37-de34f3e4e1ca",
    title: "Conjunto Masculino (Milon 2001535)",
    description: "Conjunto masculino infantil Milon.",
    category: "Roupas",
    priceCents: 0,
    imageUrl: "",
    size: "",
    storeUrl: "https://loja.milon.com.br/conjunto-masculino-2001535-311074/p",
},
{
    id: "9a4e7afa-6d6f-4e94-9e25-655a509f7490",
    title: "Jaqueta Masculina (Milon)",
    description: "Jaqueta masculina infantil Milon.",
    category: "Roupas",
    priceCents: 0,
    imageUrl: "",
    size: "",
    storeUrl: "https://loja.milon.com.br/jaqueta-masculina-2000919-280379/p",
},
{
    id: "5af1d775-cfe9-4f09-96f3-d0bcd5ba1755",
    title: "Colete Masculino (Milon)",
    description: "Colete masculino infantil Milon.",
    category: "Roupas",
    priceCents: 0,
    imageUrl: "",
    size: "",
    storeUrl: "https://loja.milon.com.br/colete-masculino-14761-202451/p",
},
{
    id: "584c33e1-be37-4f9a-b5d3-29d0d2ad9f3b",
    title: "Camisa Masculina (Milon 2001587)",
    description: "Camisa masculina infantil Milon.",
    category: "Roupas",
    priceCents: 0,
    imageUrl: "",
    size: "",
    storeUrl: "https://loja.milon.com.br/camisa-masculina-2001587-316676/p",
},
{
    id: "56b0966f-e1ce-4bab-8b2c-9d34a7c82cbb",
    title: "Camisa Masculina (Milon 2001585)",
    description: "Camisa masculina infantil Milon.",
    category: "Roupas",
    priceCents: 0,
    imageUrl: "",
    size: "",
    storeUrl: "https://loja.milon.com.br/camisa-masculina-2001585-310014/p",
},
{
    id: "0e3fea5a-d9fd-4c09-9160-61b794484143",
    title: "Conjunto Infantil Menino em Moletom - Hering",
    description: "Conjunto infantil masculino em moletom, Hering.",
    category: "Roupas",
    priceCents: 0,
    imageUrl: "",
    size: "",
    storeUrl: "https://www.hering.com.br/conjunto-infantil-menino-em-moletom-5atk2men/p",
},
{
    id: "f4712c67-560d-488a-b7d3-82d0c16fa535",
    title: "Conjunto de Moletom Infantil Menino com Estampa - Hering",
    description: "Conjunto de moletom infantil masculino estampado, Hering.",
    category: "Roupas",
    priceCents: 0,
    imageUrl: "",
    size: "",
    storeUrl: "https://www.hering.com.br/conjunto-de-moletom-infantil-menino-com-estampa-5bdn1gsn/p",
},
{
    id: "e405b6be-6488-40a9-8eb1-1b19e85157dd",
    title: "Calça Jeans Mini Indigo Black - Reserva Mini",
    description: "Calça jeans infantil Reserva Mini, cor indigo black.",
    category: "Roupas",
    priceCents: 0,
    imageUrl: "",
    size: "",
    storeUrl: "https://www.usereserva.com/calca-jeans-mini-indigo-black-0065088-040/p",
},
{
    id: "771d437f-b02d-4e10-a3d5-092281abaeaa",
    title: "Calça Mini Jeans Skinny Destroyed - Reserva Mini",
    description: "Calça jeans skinny destroyed infantil, Reserva Mini.",
    category: "Roupas",
    priceCents: 0,
    imageUrl: "",
    size: "",
    storeUrl: "https://www.usereserva.com/calca-mini-jeans-skinny-destroyed-0098253-330/p",
},
{
    id: "6ab696fe-38e8-44d0-aff5-e37dd95c9360",
    title: "Camisa Mini ML TP Flame Xadrez Jim - Reserva Mini",
    description: "Camisa manga longa xadrez estampa Jim, Reserva Mini.",
    category: "Roupas",
    priceCents: 0,
    imageUrl: "",
    size: "",
    storeUrl: "https://www.usereserva.com/camisa-mini-ml-tp-flame-xadrez-jim-0101479-195/p",
},
{
    id: "6bf06157-8d8f-494a-aae2-ab9a47706ad0",
    title: "Camisa Mini MC TP Sierra (195) - Reserva Mini",
    description: "Camisa manga curta estampa Sierra, Reserva Mini.",
    category: "Roupas",
    priceCents: 0,
    imageUrl: "",
    size: "",
    storeUrl: "https://www.usereserva.com/camisa-mini-mc-tp-sierra-0102153-396/p?skuId=637202",
},
{
    id: "d90ba742-407d-44d7-952a-123401fce616",
    title: "Camisa Mini ML TP Linho Tinturado - Reserva Mini",
    description: "Camisa manga longa em linho tinturado, Reserva Mini.",
    category: "Roupas",
    priceCents: 0,
    imageUrl: "",
    size: "",
    storeUrl: "https://www.usereserva.com/camisa-mini-ml-tp-linho-tinturado-0089213-513/p",
},
{
    id: "f6f5e4de-e8a8-477c-b86a-3175e0400783",
    title: "Camisa Mini MC Tinturada Linho Pienza - Reserva Mini",
    description: "Camisa manga curta tinturada de linho, estampa Pienza, Reserva Mini.",
    category: "Roupas",
    priceCents: 0,
    imageUrl: "",
    size: "",
    storeUrl: "https://www.usereserva.com/camisa-mini-mc-tinturada-linho-pienza-0101454-379/p",
},
{
    id: "0d2d1364-b23e-4bad-b230-8e964cd3f57e",
    title: "Camisa Mini MC TP Sierra (040) - Reserva Mini",
    description: "Camisa manga curta estampa Sierra, Reserva Mini.",
    category: "Roupas",
    priceCents: 0,
    imageUrl: "",
    size: "",
    storeUrl: "https://www.usereserva.com/camisa-mini-mc-tp-sierra-0102153-040/p",
},
{
    id: "5e55792f-2904-449e-8ae3-41d8999c9975",
    title: "Camisa Mini ML TP Nova Paraty - Reserva Mini",
    description: "Camisa manga longa estampa Nova Paraty, Reserva Mini.",
    category: "Roupas",
    priceCents: 0,
    imageUrl: "",
    size: "",
    storeUrl: "https://www.usereserva.com/camisa-mini-ml-tp-nova-paraty-0088388-002/p?skuId=554813",
},
{
    id: "1dd7b07e-4e64-4a14-a2eb-af4739c1bc5d",
    title: "Camisa Mini ML Oxford Color (312) - Reserva Mini",
    description: "Camisa manga longa oxford color, Reserva Mini.",
    category: "Roupas",
    priceCents: 0,
    imageUrl: "",
    size: "",
    storeUrl: "https://www.usereserva.com/camisa-mini-ml-oxford-color-0087193-312/p",
},
{
    id: "acdadf0c-eebb-45ac-af1e-3accc66f4bf5",
    title: "Camisa Mini ML Oxford Color (919) - Reserva Mini",
    description: "Camisa manga longa oxford color, Reserva Mini.",
    category: "Roupas",
    priceCents: 0,
    imageUrl: "",
    size: "",
    storeUrl: "https://www.usereserva.com/camisa-mini-ml-oxford-color-0083325-919/p",
},
{
    id: "d4741a4c-1624-4e44-b067-719437f19f19",
    title: "Conjunto Adidas Marvel Spider-Man Infantil",
    description: "Conjunto infantil Adidas Marvel Homem-Aranha.",
    category: "Roupas",
    priceCents: 0,
    imageUrl: "",
    size: "",
    storeUrl: "https://www.magicfeet.com.br/conjunto-adidas-marvel-spider-man-infantil-jl917-9-900/p",
},
{
    id: "f73d635f-7ffc-4017-a7cd-169f5384d660",
    title: "Conjunto Memórias Infantil Masculino Off White - Tres é Já",
    description: "Conjunto infantil masculino com camisa e bermuda, Tres é Já.",
    category: "Roupas",
    priceCents: 0,
    imageUrl: "",
    size: "",
    storeUrl: "https://www.treseja.com.br/conjunto-memorias-infantil-masculino-com-camisa-e-bermuda-off-white-tres-e-ja-art-62381_dig303",
},
{
    id: "622a25fa-aa42-4e7a-9eb4-63e96671d6c6",
    title: "Conjunto Humor Infantil com Blusão e Calça Bege - Tres é Já",
    description: "Conjunto infantil com blusão e calça, cor bege, Tres é Já.",
    category: "Roupas",
    priceCents: 0,
    imageUrl: "",
    size: "",
    storeUrl: "https://www.treseja.com.br/conjunto-humor-infantil-com-blusao-e-calca-bege-tres-e-ja-bege-art-62469_DIG359",
},
{
    id: "f59b7899-808e-4707-b7e2-a18c7eb86929",
    title: "Conjunto Infantil Masculino com Blusão e Calça Humor Bege - Tres é Já",
    description: "Conjunto infantil masculino com blusão e calça, cor bege, Tres é Já.",
    category: "Roupas",
    priceCents: 0,
    imageUrl: "",
    size: "",
    storeUrl: "https://www.treseja.com.br/conjunto-infantil-masculino-com-blusao-e-calca-humor-bege-tres-e-ja-bege-art-62470_120304",
},
{
    id: "2b82c6aa-8825-4152-b8ba-395a755407e2",
    title: "Conjunto Infantil de Camiseta e Bermuda Baguette Marrom - Tres é Já",
    description: "Conjunto infantil com camiseta e bermuda, cor marrom, Tres é Já.",
    category: "Roupas",
    priceCents: 0,
    imageUrl: "",
    size: "",
    storeUrl: "https://www.treseja.com.br/conjunto-infantil-de-camiseta-e-bermuda-baguette-marrom-tres-e-ja-marrom-art-62446_151220",
},
{
    id: "d936450f-6a7b-4ef1-97c3-f299ca58a6a9",
    title: "Conjunto Solar Infantil Masculino Amarelo - Tres é Já",
    description: "Conjunto infantil masculino com camisa e short, cor amarelo, Tres é Já.",
    category: "Roupas",
    priceCents: 0,
    imageUrl: "",
    size: "",
    storeUrl: "https://www.treseja.com.br/conjunto-solar-infantil-masculino-com-camisa-e-short-amarelo-tres-e-ja-art-62417_dig326",
},
{
    id: "684e49d4-d9f2-4da4-82f5-aea378e00739",
    title: "Conjunto Gatos Infantil Masculino Azul Claro - Tres é Já",
    description: "Conjunto infantil masculino com camisa e bermuda, cor azul claro, Tres é Já.",
    category: "Roupas",
    priceCents: 0,
    imageUrl: "",
    size: "",
    storeUrl: "https://www.treseja.com.br/conjunto-gatos-infantil-masculino-com-camisa-e-bermuda-azul-claro-tres-e-ja-art-62424_134308",
},
{
    id: "bde3e58c-e17d-46d7-8a43-934235cdb06c",
    title: "Conjunto Selva Infantil Masculino Preto - Tres é Já",
    description: "Conjunto infantil masculino com camisa e bermuda, cor preto, Tres é Já.",
    category: "Roupas",
    priceCents: 0,
    imageUrl: "",
    size: "",
    storeUrl: "https://www.treseja.com.br/conjunto-selva-infantil-masculino-com-camisa-e-bermuda-preto-tres-e-ja-art-62320_008910",
},
{
    id: "41559c44-1be0-41d2-b588-44bdd924ccaa",
    title: "Conjunto Infantil para Menino Omar Cinza - Tres é Já",
    description: "Conjunto infantil masculino com camisa e short, cor cinza, Tres é Já.",
    category: "Roupas",
    priceCents: 0,
    imageUrl: "",
    size: "",
    storeUrl: "https://www.treseja.com.br/conjunto-infantil-para-menino-com-camisa-e-short-omar-cinza-art-62243_165101",
},
{
    id: "7543c48d-5a18-41ef-9d33-fce8a5149b80",
    title: "Conjunto Infantil para Menino Safari Off White - Tres é Já",
    description: "Conjunto infantil masculino com camisa e bermuda, cor off white, Tres é Já.",
    category: "Roupas",
    priceCents: 0,
    imageUrl: "",
    size: "",
    storeUrl: "https://www.treseja.com.br/conjunto-infantil-para-menino-com-camisa-e-bermuda-safari-off-white-art-62241_DIG252",
},
{
    id: "8da859db-9f6f-48f1-82e0-4ddd43f0dca5",
    title: "Pijama Manga Longa Soft Menino Futebol - Puket",
    description: "Pijama manga longa em soft, estampa futebol, Puket.",
    category: "Roupas",
    priceCents: 0,
    imageUrl: "",
    size: "",
    storeUrl: "https://www.puket.com.br/pijama-manga-longa-soft-menino-tuba-futebol-030403063-390/p?skuId=530056",
},
{
    id: "a718b6ca-3fea-42ff-b5ff-4f167adfbbe2",
    title: "Macacão Manga Longa Menino Dino Astronauta - Puket",
    description: "Macacão manga longa, estampa dino astronauta, Puket.",
    category: "Roupas",
    priceCents: 0,
    imageUrl: "",
    size: "",
    storeUrl: "https://www.puket.com.br/macacao-manga-longa-menino-dino-astronauta-030403072-055/p?skuId=529976",
},
{
    id: "5ea19176-5eef-4ca1-9494-81677cf07b52",
    title: "Pijama Manga Longa Soft Menino Dino Astronauta - Puket",
    description: "Pijama manga longa em soft, estampa dino astronauta, Puket.",
    category: "Roupas",
    priceCents: 0,
    imageUrl: "",
    size: "",
    storeUrl: "https://www.puket.com.br/pijama-manga-longa-soft-menino-dino-astronauta-030403054-055/p?skuId=529604",
},
{
    id: "5cb24527-8b70-48a6-b981-7c7068cd70f6",
    title: "Pijama Manga Longa Viscolycra Menino Capivara Vibes - Puket",
    description: "Pijama manga longa em viscolycra, estampa capivara vibes, Puket.",
    category: "Roupas",
    priceCents: 0,
    imageUrl: "",
    size: "",
    storeUrl: "https://www.puket.com.br/pijama-manga-longa-viscolycra-menino-capivara-vibes-030402997-727/p?skuId=525292",
},
{
    id: "aec6e730-4ec7-45f5-8a77-ccf02badd280",
    title: "Pijama Manga Longa Ultra Visco Menino Dino Astronauta - Puket",
    description: "Pijama manga longa em ultra visco, estampa dino astronauta, Puket.",
    category: "Roupas",
    priceCents: 0,
    imageUrl: "",
    size: "",
    storeUrl: "https://www.puket.com.br/pijama-manga-longa-ultra-visco-menino-dino-astronauta-030403073-055/p?skuId=529615",
},
{
    id: "8903eb6a-ab62-40b2-ada2-5408d29d7650",
    title: "Conjunto Camiseta e Shorts com Listras Sprinter - Adidas",
    description: "Conjunto infantil Adidas de camiseta e shorts com listras, modelo Sprinter.",
    category: "Roupas",
    priceCents: 0,
    imageUrl: "",
    size: "",
    storeUrl: "https://www.adidas.com.br/conjunto-de-camiseta-e-shorts-com-listras-sprinter/KT4364.html",
},
{
    id: "5bde5b26-d153-4cb0-aafe-b5ff67a5ce1f",
    title: "Conjunto Camisetas Adidas Marvel Homem-Aranha",
    description: "Conjunto infantil de camisetas Adidas Marvel Homem-Aranha.",
    category: "Roupas",
    priceCents: 0,
    imageUrl: "",
    size: "",
    storeUrl: "https://www.adidas.com.br/conjunto-camisetas-adidas-marvel-homem-aranha/JZ3550.html",
},
{
    id: "9aa03bc2-c425-4c2d-9c0b-67ad266cd7f8",
    title: "Conjunto Shorts e Camiseta Infantil - Adidas",
    description: "Conjunto infantil Adidas de shorts e camiseta.",
    category: "Roupas",
    priceCents: 0,
    imageUrl: "",
    size: "",
    storeUrl: "https://www.adidas.com.br/conjunto-shorts-camiseta-infantil/JI5812.html",
},
{
    id: "3ca10b90-1d41-4bba-a72b-76906ea6cbc3",
    title: "Macaquinho de Praia Toddler Tubarão com Proteção UV 50 - Tip Top",
    description: "Macaquinho de praia toddler, estampa tubarão, com boia elastano e proteção UV 50.",
    category: "Roupas",
    priceCents: 0,
    imageUrl: "",
    size: "",
    storeUrl: "https://www.tiptop.com.br/macaquinho-praia-toddler-tubarao-boia-elastano-protecao-uv-50-tip-top-p374506",
},
{
    id: "e180a949-94f0-493f-a9b1-76d378eb3e69",
    title: "Kit Praia 3 Peças Toddler Mundo dos Dinos UV 50 - Tip Top",
    description: "Kit praia com 3 peças toddler, estampa mundo dos dinos, lycra com proteção UV 50.",
    category: "Roupas",
    priceCents: 0,
    imageUrl: "",
    size: "",
    storeUrl: "https://www.tiptop.com.br/kit-praia-3-pecas-toddler-mundo-dos-dinos-lycra-protecao-uv-50-tip-top-p374420",
},
];

async function main() {
  for (const item of items) {
    await prisma.item.upsert({
      where: { storeUrl: item.storeUrl },
      create: item,
      update: {
        title: item.title,
        description: item.description,
        category: item.category,
        priceCents: item.priceCents,
        size: item.size,
      },
    });
  }
  console.log(`Seed: ${items.length} presentes sincronizados (upsert por storeUrl).`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
