import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const items = [
{
    title: "Tênis Adidas VL Court Woody EL C Infantil",
    description: "Tênis infantil Adidas VL Court Woody EL C.",
    category: "Calçados",
    priceCents: 0,
    imageUrl: "",
    storeUrl: "https://www.magicfeet.com.br/tenis-adidas-vl-court-woody-el-c-infantil-jq438-2-400/p",
},
{
    title: "Tênis Adidas VL Court 3.0 CF Infantil",
    description: "Tênis infantil Adidas VL Court 3.0 CF.",
    category: "Calçados",
    priceCents: 0,
    imageUrl: "",
    storeUrl: "https://www.magicfeet.com.br/tenis-adidas-vl-court-3-0-cf-infantil-ih396-6-100/p",
},
{
    title: "Tênis Veja Small Volley Suede Infantil",
    description: "Tênis infantil Veja Small Volley Suede.",
    category: "Calçados",
    priceCents: 0,
    imageUrl: "",
    storeUrl: "https://www.magicfeet.com.br/tenis-veja-small-volley-suede-infantil-21018-0-300/p",
},
{
    title: "Tênis Converse Chuck Taylor All Star Velcro TD Infantil",
    description: "Tênis infantil Converse Chuck Taylor All Star com velcro.",
    category: "Calçados",
    priceCents: 0,
    imageUrl: "",
    storeUrl: "https://www.magicfeet.com.br/tenis-converse-chuck-taylor-all-star-velcro-td-infantil-ck041-8-004/p",
},
{
    title: "Tênis Adidas VL Court 3.0 CF Infantil",
    description: "Tênis infantil Adidas VL Court 3.0 CF.",
    category: "Calçados",
    priceCents: 0,
    imageUrl: "",
    storeUrl: "https://www.magicfeet.com.br/tenis-adidas-vl-court-3-0-cf-infantil-id915-6-001/p",
},
{
    title: "Chinelo Nike Kawa Slide BT Infantil",
    description: "Chinelo infantil Nike Kawa Slide.",
    category: "Calçados",
    priceCents: 0,
    imageUrl: "",
    storeUrl: "https://www.magicfeet.com.br/chinelo-nike-kawa-slide-bt-infantil-fj881-1-401/p",
},
{
    title: "Sandália Crocs Crocband Clog TD Infantil",
    description: "Sandália infantil Crocs Crocband.",
    category: "Calçados",
    priceCents: 0,
    imageUrl: "",
    storeUrl: "https://www.magicfeet.com.br/sandalia-crocs-crocband-clog-td-infantil-20700-5-485/p",
},
{
    title: "Sandália Crocs Crocband Clog T Infantil",
    description: "Sandália infantil Crocs Crocband.",
    category: "Calçados",
    priceCents: 0,
    imageUrl: "",
    storeUrl: "https://www.magicfeet.com.br/sandalia-crocs-crocband-clog-t-infantil-20700-5-126/p",
},
{
    title: "Sandália Infantil Bibi Baby Soft II Marrom",
    description: "Sandália infantil Bibi Baby Soft II.",
    category: "Calçados",
    priceCents: 0,
    imageUrl: "",
    storeUrl: "https://www.bibi.com/sandalia-infantil-bibi-baby-soft-ii-marrom/p",
},
{
    title: "Tênis Masculino CB Vol.2",
    description: "Tênis masculino infantil CB Vol.2.",
    category: "Calçados",
    priceCents: 0,
    imageUrl: "",
    storeUrl: "https://loja.milon.com.br/tenis-masculino-cb-vol2-546-307971/p",
},

// ===================== BRINQUEDOS =====================
{
    title: "Assento Redutor Privadinha Sanitário Infantil",
    description: "Assento redutor infantil para vaso sanitário.",
    category: "Brinquedos",
    priceCents: 0,
    imageUrl: "",
    storeUrl: "https://www.amazon.com.br/Assento-Redutor-Privadinha-Sanit%C3%A1rio-Infantil/dp/B0FKBD4BNG/",
},
{
    title: "Conjunto de Carrinhos Hot Wheels Mattel",
    description: "Kit com conjunto de carrinhos Hot Wheels da Mattel.",
    category: "Brinquedos",
    priceCents: 0,
    imageUrl: "",
    storeUrl: "https://www.amazon.com.br/Conjunto-Carrinhos-Wheels-Mattel-H7045/dp/B0007R4J30/",
},
{
    title: "Triciclo Infantil com Cestinha",
    description: "Triciclo infantil masculino com cestinha.",
    category: "Brinquedos",
    priceCents: 0,
    imageUrl: "",
    storeUrl: "https://www.amazon.com.br/Triciclo-Infantil-Cestinha-Bicicleta-Masculina/dp/B0H2JQZX5K/",
},
{
    title: "Carrinho de Rolimã Infantil Vermelho",
    description: "Carrinho de rolimã infantil na cor vermelha.",
    category: "Brinquedos",
    priceCents: 0,
    imageUrl: "",
    storeUrl: "https://www.amazon.com.br/Carrinho-Infantil-Rodopio-Suporta-Vermelho/dp/B0GZSCLKYF/",
},
{
    title: "Patinete Infantil Aviãozinho Ajustável",
    description: "Patinete infantil formato aviãozinho, ajustável, com luz e som.",
    category: "Brinquedos",
    priceCents: 0,
    imageUrl: "",
    storeUrl: "https://www.amazon.com.br/DM-Toys-Patinete-Aviaozinho-Ajustavel/dp/B0DJS66HVG/",
},
{
    title: "Blocos Magnéticos de Construção",
    description: "Kit de blocos magnéticos para construção.",
    category: "Brinquedos",
    priceCents: 0,
    imageUrl: "",
    storeUrl: "https://www.amazon.com.br/Blocos-Constru%C3%A7%C3%A3o-Magn%C3%A9ticos-Brastoy-Brinquedos/dp/B097K16GKC/",
},
{
    title: "Mini Quadriciclo Elétrico Infantil 6V",
    description: "Mini quadriciclo elétrico infantil a bateria 6V, com luz e música.",
    category: "Brinquedos",
    priceCents: 0,
    imageUrl: "",
    storeUrl: "https://www.mercadolivre.com.br/mini-quadriciclo-eletrico-infantil-bateria-6v-luz-e-musica-cor-laranja-voltagem-do-carregador-110v220v-brinqkids/p/MLB43400696",
},
{
    title: "Mini Moto Elétrica Infantil 6V Preta",
    description: "Mini moto elétrica infantil 6V, cor preta, com empurrador.",
    category: "Brinquedos",
    priceCents: 0,
    imageUrl: "",
    storeUrl: "https://www.mercadolivre.com.br/mini-moto-eletrica-infantil-6v-preta-speed-com-empurrador-preto/p/MLB62101177",
},
{
    title: "Bateria Musical Infantil Rock Party",
    description: "Instrumento infantil bateria musical Rock Party, DM Toys.",
    category: "Brinquedos",
    priceCents: 0,
    imageUrl: "",
    storeUrl: "https://www.mercadolivre.com.br/bateria-musical-instrumento-infantil-rock-party-preta-dm-toys-dmt6066pr/p/MLB23531681",
},
{
    title: "Mochila Kids Carros Masterbag",
    description: "Mochila infantil tema carros, Masterbag Kids.",
    category: "Brinquedos",
    priceCents: 0,
    imageUrl: "",
    storeUrl: "https://www.bebefacil.com.br/produto/mochila-kids-carros-masterbag-kids-4725",
},

// ===================== ROUPAS =====================
{
    title: "Conjunto Masculino (Milon 2001697)",
    description: "Conjunto masculino infantil Milon.",
    category: "Roupas",
    priceCents: 0,
    imageUrl: "",
    storeUrl: "https://loja.milon.com.br/conjunto-masculino-2001697-319332/p",
},
{
    title: "Conjunto Masculino (Milon 3000937)",
    description: "Conjunto masculino infantil Milon.",
    category: "Roupas",
    priceCents: 0,
    imageUrl: "",
    storeUrl: "https://loja.milon.com.br/conjunto-masculino-3000937-315473/p",
},
{
    title: "Conjunto Masculino (Milon 2001708)",
    description: "Conjunto masculino infantil Milon.",
    category: "Roupas",
    priceCents: 0,
    imageUrl: "",
    storeUrl: "https://loja.milon.com.br/conjunto-masculino-2001708-308376/p",
},
{
    title: "Conjunto Masculino (Milon 3000715)",
    description: "Conjunto masculino infantil Milon.",
    category: "Roupas",
    priceCents: 0,
    imageUrl: "",
    storeUrl: "https://loja.milon.com.br/conjunto-masculino-3000715-306882/p",
},
{
    title: "Conjunto Masculino (Milon 2001325)",
    description: "Conjunto masculino infantil Milon.",
    category: "Roupas",
    priceCents: 0,
    imageUrl: "",
    storeUrl: "https://loja.milon.com.br/conjunto-masculino-2001325-299471/p",
},
{
    title: "Conjunto Masculino (Milon 2001532)",
    description: "Conjunto masculino infantil Milon.",
    category: "Roupas",
    priceCents: 0,
    imageUrl: "",
    storeUrl: "https://loja.milon.com.br/conjunto-masculino-2001532-318542/p",
},
{
    title: "Conjunto Masculino (Milon 2001535)",
    description: "Conjunto masculino infantil Milon.",
    category: "Roupas",
    priceCents: 0,
    imageUrl: "",
    storeUrl: "https://loja.milon.com.br/conjunto-masculino-2001535-311074/p",
},
{
    title: "Jaqueta Masculina (Milon)",
    description: "Jaqueta masculina infantil Milon.",
    category: "Roupas",
    priceCents: 0,
    imageUrl: "",
    storeUrl: "https://loja.milon.com.br/jaqueta-masculina-2000919-280379/p",
},
{
    title: "Colete Masculino (Milon)",
    description: "Colete masculino infantil Milon.",
    category: "Roupas",
    priceCents: 0,
    imageUrl: "",
    storeUrl: "https://loja.milon.com.br/colete-masculino-14761-202451/p",
},
{
    title: "Camisa Masculina (Milon 2001587)",
    description: "Camisa masculina infantil Milon.",
    category: "Roupas",
    priceCents: 0,
    imageUrl: "",
    storeUrl: "https://loja.milon.com.br/camisa-masculina-2001587-316676/p",
},
{
    title: "Camisa Masculina (Milon 2001585)",
    description: "Camisa masculina infantil Milon.",
    category: "Roupas",
    priceCents: 0,
    imageUrl: "",
    storeUrl: "https://loja.milon.com.br/camisa-masculina-2001585-310014/p",
},
{
    title: "Conjunto Infantil Menino em Moletom - Hering",
    description: "Conjunto infantil masculino em moletom, Hering.",
    category: "Roupas",
    priceCents: 0,
    imageUrl: "",
    storeUrl: "https://www.hering.com.br/conjunto-infantil-menino-em-moletom-5atk2men/p",
},
{
    title: "Conjunto de Moletom Infantil Menino com Estampa - Hering",
    description: "Conjunto de moletom infantil masculino estampado, Hering.",
    category: "Roupas",
    priceCents: 0,
    imageUrl: "",
    storeUrl: "https://www.hering.com.br/conjunto-de-moletom-infantil-menino-com-estampa-5bdn1gsn/p",
},
{
    title: "Calça Jeans Mini Indigo Black - Reserva Mini",
    description: "Calça jeans infantil Reserva Mini, cor indigo black.",
    category: "Roupas",
    priceCents: 0,
    imageUrl: "",
    storeUrl: "https://www.usereserva.com/calca-jeans-mini-indigo-black-0065088-040/p",
},
{
    title: "Calça Mini Jeans Skinny Destroyed - Reserva Mini",
    description: "Calça jeans skinny destroyed infantil, Reserva Mini.",
    category: "Roupas",
    priceCents: 0,
    imageUrl: "",
    storeUrl: "https://www.usereserva.com/calca-mini-jeans-skinny-destroyed-0098253-330/p",
},
{
    title: "Camisa Mini ML TP Flame Xadrez Jim - Reserva Mini",
    description: "Camisa manga longa xadrez estampa Jim, Reserva Mini.",
    category: "Roupas",
    priceCents: 0,
    imageUrl: "",
    storeUrl: "https://www.usereserva.com/camisa-mini-ml-tp-flame-xadrez-jim-0101479-195/p",
},
{
    title: "Camisa Mini MC TP Sierra (195) - Reserva Mini",
    description: "Camisa manga curta estampa Sierra, Reserva Mini.",
    category: "Roupas",
    priceCents: 0,
    imageUrl: "",
    storeUrl: "https://www.usereserva.com/camisa-mini-mc-tp-sierra-0102153-396/p?skuId=637202",
},
{
    title: "Camisa Mini ML TP Linho Tinturado - Reserva Mini",
    description: "Camisa manga longa em linho tinturado, Reserva Mini.",
    category: "Roupas",
    priceCents: 0,
    imageUrl: "",
    storeUrl: "https://www.usereserva.com/camisa-mini-ml-tp-linho-tinturado-0089213-513/p",
},
{
    title: "Camisa Mini MC Tinturada Linho Pienza - Reserva Mini",
    description: "Camisa manga curta tinturada de linho, estampa Pienza, Reserva Mini.",
    category: "Roupas",
    priceCents: 0,
    imageUrl: "",
    storeUrl: "https://www.usereserva.com/camisa-mini-mc-tinturada-linho-pienza-0101454-379/p",
},
{
    title: "Camisa Mini MC TP Sierra (040) - Reserva Mini",
    description: "Camisa manga curta estampa Sierra, Reserva Mini.",
    category: "Roupas",
    priceCents: 0,
    imageUrl: "",
    storeUrl: "https://www.usereserva.com/camisa-mini-mc-tp-sierra-0102153-040/p",
},
{
    title: "Camisa Mini ML TP Nova Paraty - Reserva Mini",
    description: "Camisa manga longa estampa Nova Paraty, Reserva Mini.",
    category: "Roupas",
    priceCents: 0,
    imageUrl: "",
    storeUrl: "https://www.usereserva.com/camisa-mini-ml-tp-nova-paraty-0088388-002/p?skuId=554813",
},
{
    title: "Camisa Mini ML Oxford Color (312) - Reserva Mini",
    description: "Camisa manga longa oxford color, Reserva Mini.",
    category: "Roupas",
    priceCents: 0,
    imageUrl: "",
    storeUrl: "https://www.usereserva.com/camisa-mini-ml-oxford-color-0087193-312/p",
},
{
    title: "Camisa Mini ML Oxford Color (919) - Reserva Mini",
    description: "Camisa manga longa oxford color, Reserva Mini.",
    category: "Roupas",
    priceCents: 0,
    imageUrl: "",
    storeUrl: "https://www.usereserva.com/camisa-mini-ml-oxford-color-0083325-919/p",
},
{
    title: "Conjunto Adidas Marvel Spider-Man Infantil",
    description: "Conjunto infantil Adidas Marvel Homem-Aranha.",
    category: "Roupas",
    priceCents: 0,
    imageUrl: "",
    storeUrl: "https://www.magicfeet.com.br/conjunto-adidas-marvel-spider-man-infantil-jl917-9-900/p",
},
{
    title: "Conjunto Memórias Infantil Masculino Off White - Tres é Já",
    description: "Conjunto infantil masculino com camisa e bermuda, Tres é Já.",
    category: "Roupas",
    priceCents: 0,
    imageUrl: "",
    storeUrl: "https://www.treseja.com.br/conjunto-memorias-infantil-masculino-com-camisa-e-bermuda-off-white-tres-e-ja-art-62381_dig303",
},
{
    title: "Conjunto Humor Infantil com Blusão e Calça Bege - Tres é Já",
    description: "Conjunto infantil com blusão e calça, cor bege, Tres é Já.",
    category: "Roupas",
    priceCents: 0,
    imageUrl: "",
    storeUrl: "https://www.treseja.com.br/conjunto-humor-infantil-com-blusao-e-calca-bege-tres-e-ja-bege-art-62469_DIG359",
},
{
    title: "Conjunto Infantil Masculino com Blusão e Calça Humor Bege - Tres é Já",
    description: "Conjunto infantil masculino com blusão e calça, cor bege, Tres é Já.",
    category: "Roupas",
    priceCents: 0,
    imageUrl: "",
    storeUrl: "https://www.treseja.com.br/conjunto-infantil-masculino-com-blusao-e-calca-humor-bege-tres-e-ja-bege-art-62470_120304",
},
{
    title: "Conjunto Infantil de Camiseta e Bermuda Baguette Marrom - Tres é Já",
    description: "Conjunto infantil com camiseta e bermuda, cor marrom, Tres é Já.",
    category: "Roupas",
    priceCents: 0,
    imageUrl: "",
    storeUrl: "https://www.treseja.com.br/conjunto-infantil-de-camiseta-e-bermuda-baguette-marrom-tres-e-ja-marrom-art-62446_151220",
},
{
    title: "Conjunto Solar Infantil Masculino Amarelo - Tres é Já",
    description: "Conjunto infantil masculino com camisa e short, cor amarelo, Tres é Já.",
    category: "Roupas",
    priceCents: 0,
    imageUrl: "",
    storeUrl: "https://www.treseja.com.br/conjunto-solar-infantil-masculino-com-camisa-e-short-amarelo-tres-e-ja-art-62417_dig326",
},
{
    title: "Conjunto Gatos Infantil Masculino Azul Claro - Tres é Já",
    description: "Conjunto infantil masculino com camisa e bermuda, cor azul claro, Tres é Já.",
    category: "Roupas",
    priceCents: 0,
    imageUrl: "",
    storeUrl: "https://www.treseja.com.br/conjunto-gatos-infantil-masculino-com-camisa-e-bermuda-azul-claro-tres-e-ja-art-62424_134308",
},
{
    title: "Conjunto Selva Infantil Masculino Preto - Tres é Já",
    description: "Conjunto infantil masculino com camisa e bermuda, cor preto, Tres é Já.",
    category: "Roupas",
    priceCents: 0,
    imageUrl: "",
    storeUrl: "https://www.treseja.com.br/conjunto-selva-infantil-masculino-com-camisa-e-bermuda-preto-tres-e-ja-art-62320_008910",
},
{
    title: "Conjunto Infantil para Menino Omar Cinza - Tres é Já",
    description: "Conjunto infantil masculino com camisa e short, cor cinza, Tres é Já.",
    category: "Roupas",
    priceCents: 0,
    imageUrl: "",
    storeUrl: "https://www.treseja.com.br/conjunto-infantil-para-menino-com-camisa-e-short-omar-cinza-art-62243_165101",
},
{
    title: "Conjunto Infantil para Menino Safari Off White - Tres é Já",
    description: "Conjunto infantil masculino com camisa e bermuda, cor off white, Tres é Já.",
    category: "Roupas",
    priceCents: 0,
    imageUrl: "",
    storeUrl: "https://www.treseja.com.br/conjunto-infantil-para-menino-com-camisa-e-bermuda-safari-off-white-art-62241_DIG252",
},
{
    title: "Pijama Manga Longa Soft Menino Futebol - Puket",
    description: "Pijama manga longa em soft, estampa futebol, Puket.",
    category: "Roupas",
    priceCents: 0,
    imageUrl: "",
    storeUrl: "https://www.puket.com.br/pijama-manga-longa-soft-menino-tuba-futebol-030403063-390/p?skuId=530056",
},
{
    title: "Macacão Manga Longa Menino Dino Astronauta - Puket",
    description: "Macacão manga longa, estampa dino astronauta, Puket.",
    category: "Roupas",
    priceCents: 0,
    imageUrl: "",
    storeUrl: "https://www.puket.com.br/macacao-manga-longa-menino-dino-astronauta-030403072-055/p?skuId=529976",
},
{
    title: "Pijama Manga Longa Soft Menino Dino Astronauta - Puket",
    description: "Pijama manga longa em soft, estampa dino astronauta, Puket.",
    category: "Roupas",
    priceCents: 0,
    imageUrl: "",
    storeUrl: "https://www.puket.com.br/pijama-manga-longa-soft-menino-dino-astronauta-030403054-055/p?skuId=529604",
},
{
    title: "Pijama Manga Longa Viscolycra Menino Capivara Vibes - Puket",
    description: "Pijama manga longa em viscolycra, estampa capivara vibes, Puket.",
    category: "Roupas",
    priceCents: 0,
    imageUrl: "",
    storeUrl: "https://www.puket.com.br/pijama-manga-longa-viscolycra-menino-capivara-vibes-030402997-727/p?skuId=525292",
},
{
    title: "Pijama Manga Longa Ultra Visco Menino Dino Astronauta - Puket",
    description: "Pijama manga longa em ultra visco, estampa dino astronauta, Puket.",
    category: "Roupas",
    priceCents: 0,
    imageUrl: "",
    storeUrl: "https://www.puket.com.br/pijama-manga-longa-ultra-visco-menino-dino-astronauta-030403073-055/p?skuId=529615",
},
{
    title: "Conjunto Camiseta e Shorts com Listras Sprinter - Adidas",
    description: "Conjunto infantil Adidas de camiseta e shorts com listras, modelo Sprinter.",
    category: "Roupas",
    priceCents: 0,
    imageUrl: "",
    storeUrl: "https://www.adidas.com.br/conjunto-de-camiseta-e-shorts-com-listras-sprinter/KT4364.html",
},
{
    title: "Conjunto Camisetas Adidas Marvel Homem-Aranha",
    description: "Conjunto infantil de camisetas Adidas Marvel Homem-Aranha.",
    category: "Roupas",
    priceCents: 0,
    imageUrl: "",
    storeUrl: "https://www.adidas.com.br/conjunto-camisetas-adidas-marvel-homem-aranha/JZ3550.html",
},
{
    title: "Conjunto Shorts e Camiseta Infantil - Adidas",
    description: "Conjunto infantil Adidas de shorts e camiseta.",
    category: "Roupas",
    priceCents: 0,
    imageUrl: "",
    storeUrl: "https://www.adidas.com.br/conjunto-shorts-camiseta-infantil/JI5812.html",
},
{
    title: "Macaquinho de Praia Toddler Tubarão com Proteção UV 50 - Tip Top",
    description: "Macaquinho de praia toddler, estampa tubarão, com boia elastano e proteção UV 50.",
    category: "Roupas",
    priceCents: 0,
    imageUrl: "",
    storeUrl: "https://www.tiptop.com.br/macaquinho-praia-toddler-tubarao-boia-elastano-protecao-uv-50-tip-top-p374506",
},
{
    title: "Kit Praia 3 Peças Toddler Mundo dos Dinos UV 50 - Tip Top",
    description: "Kit praia com 3 peças toddler, estampa mundo dos dinos, lycra com proteção UV 50.",
    category: "Roupas",
    priceCents: 0,
    imageUrl: "",
    storeUrl: "https://www.tiptop.com.br/kit-praia-3-pecas-toddler-mundo-dos-dinos-lycra-protecao-uv-50-tip-top-p374420",
},
];

async function main() {
  const count = await prisma.item.count();
  if (count === 0) {
    await prisma.item.createMany({ data: items });
    console.log(`Seed: ${items.length} presentes inseridos.`);
  } else {
    console.log(`Seed: banco ja possui ${count} itens, pulando.`);
  }
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
